package fb

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"testing"
)

// updateCensus rewrites the generated file instead of checking it. It is the
// same -update the golden suite uses, declared here because this is the first
// generated thing in the package.
var updateCensus = flag.Bool("update", false, "rewrite the generated files instead of checking them")

// fields_gen_test.go builds the census in fields.go out of the fixtures, and
// fails when the committed census and the measured one differ.
//
// Run it with -update after changing a parser or adding a fixture:
//
//	go test ./fb -run Census -update
//
// The diff it produces is the point. A field that goes from `filled 3 of 3` to
// `filled 0 of 3` is a parser that stopped working against a page that has not
// changed, and without this it would ship as a null nobody queried.

// censusSource is one kind and the fixtures that produce a record of it.
//
// The parse functions are called rather than the engine, so this runs with no
// network and no envelope: what is being measured is what the parsers pull out
// of bytes Facebook actually sent.
type censusSource struct {
	kind  string
	from  []string
	parse func(t *testing.T, name string) any
}

func censusSources() []censusSource {
	return []censusSource{
		{"profile", []string{"page_nasa", "page_about"}, func(t *testing.T, n string) any {
			// The head goes on, because the engine puts it on: likes and
			// talking_about live on surface 3 and nowhere else, and a census
			// that skipped it would report the two of them as missing forever.
			p := parseProfile(fixtureDocs(t, n))
			applyProfileHead(&p, parseHead(fixture(t, n)))
			return p
		}},
		{"post", []string{"post_perm"}, func(t *testing.T, n string) any {
			return parsePost(fixtureDocs(t, n))
		}},
		{"photo", []string{"photo"}, func(t *testing.T, n string) any {
			return parsePhoto(fixtureDocs(t, n))
		}},
		{"video", []string{"reel", "watch_real"}, func(t *testing.T, n string) any {
			return parseVideo(fixtureDocs(t, n))
		}},
		{"group", []string{"group_big"}, func(t *testing.T, n string) any {
			return parseGroup(fixtureDocs(t, n))
		}},
		{"event", []string{"event"}, func(t *testing.T, n string) any {
			return parseEvent(fixtureDocs(t, n), parseHead(fixture(t, n)))
		}},
		{"section", []string{"page_photos", "page_events", "page_videos"}, func(t *testing.T, n string) any {
			return parseSection(fixtureDocs(t, n), Ref{ID: "100044561550831", Name: "NASA"})
		}},
		{"directory", []string{"dir_pages", "dir_blocked"}, func(t *testing.T, n string) any {
			// Each fixture gets the URL it was captured from: the letter is
			// read out of the URL, so passing the index URL for both would
			// report `letter` as never filled.
			url := "https://www.facebook.com/directory/pages/"
			if n == "dir_blocked" {
				url += "A"
			}
			return parseDirectory(url, fixture(t, n))
		}},
		{"head", []string{"page_nasa", "event", "photo"}, func(t *testing.T, n string) any {
			return parseHead(fixture(t, n))
		}},
	}
}

// measureCensus parses every fixture and counts what came out filled.
func measureCensus(t *testing.T) []Field {
	t.Helper()
	var out []Field
	for _, src := range censusSources() {
		// order keeps the fields in declaration order, which is the order the
		// struct is written in and the order somebody reading it expects.
		var order []string
		typ := map[string]string{}
		seen := map[string][]string{}
		for _, name := range src.from {
			rec := reflect.ValueOf(src.parse(t, name))
			walkFields(rec, "", map[reflect.Type]bool{}, func(path, ft string, filled bool) {
				if _, ok := typ[path]; !ok {
					order = append(order, path)
					typ[path] = ft
				}
				if filled {
					seen[path] = append(seen[path], name)
				}
			})
		}
		for _, path := range order {
			out = append(out, Field{
				Kind:     src.kind,
				Name:     path,
				Type:     typ[path],
				Filled:   len(seen[path]),
				Fixtures: len(src.from),
				Seen:     seen[path],
			})
		}
	}
	return out
}

func TestCensusMatchesTheFixtures(t *testing.T) {
	want := renderCensus(measureCensus(t))
	const path = "fields_gen.go"
	if *updateCensus {
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		t.Logf("wrote %s", path)
		return
	}
	have, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run go test ./fb -run Census -update)", path, err)
	}
	if !bytes.Equal(have, want) {
		t.Errorf("%s is not what the fixtures say.\nA field that changed from filled to empty is a parser that stopped working.\nRun: go test ./fb -run Census -update, and read the diff before committing it.", path)
	}
}

// renderCensus writes the generated file.
func renderCensus(fields []Field) []byte {
	var b bytes.Buffer
	b.WriteString(`// Code generated by go test ./fb -run Census -update. DO NOT EDIT.

package fb

// Census is every field of every record kind, measured against the fixtures in
// testdata. See fields.go for what the numbers mean and what they do not.
var Census = []Field{
`)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t{Kind: %q, Name: %q, Type: %q, Filled: %d, Fixtures: %d", f.Kind, f.Name, f.Type, f.Filled, f.Fixtures)
		if len(f.Seen) > 0 {
			s := append([]string(nil), f.Seen...)
			sort.Strings(s)
			b.WriteString(", Seen: []string{")
			for i, n := range s {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%q", n)
			}
			b.WriteString("}")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		// Returning the unformatted bytes makes the failure readable: gofmt -l
		// catches it and the file is there to look at.
		return b.Bytes()
	}
	return src
}
